### ISSUE TITLE
Error while starting OpenGothic No device

### ISSUE THREAD

**Issue by ArturAiwasan** [Try/OpenGothic#283]
```
OpenGothic v1.0 dev

---crashlog(std::system_error(No device))---
GPU: ?
#1:  - /usr/lib/libstdc++.so.6(+0xa5d69) [0x7fe835c1ed69]
#2:  - /usr/lib/libstdc++.so.6(+0xa5fcd) [0x7fe835c1efcd]
#3:  - /home/artur/Загрузки/OpenGothic-opengothic-v1.0.1527/OpenGothic/build/opengothic/libTempest.so(+0xcf2da) [0x7fe8360a02da]
#4: Tempest::VulkanApi::createDevice(char const*) - /home/artur/Загрузки/OpenGothic-opengothic-v1.0.1527/OpenGothic/build/opengothic/libTempest.so(_ZN7Tempest9VulkanApi12createDeviceEPKc+0x27) [0x7fe8361353d7]
#5: Tempest::Device::Impl::Impl(Tempest::AbstractGraphicsApi&, char const*) - /home/artur/Загрузки/OpenGothic-opengothic-v1.0.1527/OpenGothic/build/opengothic/libTempest.so(_ZN7Tempest6Device4ImplC1ERNS_19AbstractGraphicsApiEPKc+0x1b) [0x7fe836137edb]
#6: Tempest::Device::Device(Tempest::AbstractGraphicsApi&, char const*) - /home/artur/Загрузки/OpenGothic-opengothic-v1.0.1527/OpenGothic/build/opengothic/libTempest.so(_ZN7Tempest6DeviceC1ERNS_19AbstractGraphicsApiEPKc+0x32) [0x7fe836138072]
#7: main - /home/artur/Загрузки/OpenGothic-opengothic-v1.0.1527/OpenGothic/build/opengothic/Gothic2Notr(main+0x13c) [0x56151d4985fc]

[1]    56572 IOT instruction (core dumped)  ./Gothic2Notr.sh -g ~/.wine/drive_c/Games/Gothic/

```
Parametroj de komputilo:
```
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    driver: i915 v: kernel
  Device-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT
    620M/625M/630M/720M] driver: nouveau v: kernel
  Display: x11 server: X.Org v: 21.1.4 driver: X: loaded: modesetting
    gpu: i915 resolution: 1366x768~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 2000 (SNB GT1) v: 3.3 Mesa
    22.1.6
```

Povas esti eraro pro komputila malabutmenteblaj parametroj?
Can the error be due to unsupported computer parameters?
